In [126]:
X = ones(4, 4)

4x4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [127]:
θ = ones(4)

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0

In [129]:
X*θ

4-element Array{Float64,1}:
 4.0
 4.0
 4.0
 4.0

In [130]:
transpose(θ)*X

1x4 Array{Float64,2}:
 4.0  4.0  4.0  4.0

In [36]:
a*B

4-element Array{Float64,1}:
 28.0
 32.0
 36.0
 40.0

In [116]:
size(X1)[2]

2

16